version: '3.6'

services:

  rabbit:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBIT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBIT_PASS}"
    ports:
      - 8082:15672
      - 5672:5672

  mongo:
    image: mongo
    restart: always
    volumes: 
      - ~/Data/npm-miner/mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${ME_CONFIG_MONGODB_ADMINUSERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${ME_CONFIG_MONGODB_ADMINPASSWORD}"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${ME_CONFIG_MONGODB_ADMINUSERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${ME_CONFIG_MONGODB_ADMINPASSWORD}"
      ME_CONFIG_BASICAUTH_USERNAME: "${ME_CONFIG_BASICAUTH_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${ME_CONFIG_BASICAUTH_PASSWORD}"
